In [1]:
#start Numpy
import numpy as np

In [2]:
data = [1,2,3,4,5] #Data list

In [3]:
data

[1, 2, 3, 4, 5]

In [4]:
np.array(data) #mengubah list menjadi array numpy

array([1, 2, 3, 4, 5])

In [6]:
np.arange(0,10) #membuat data array numpy secara otomatis

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2) #2 merupakan kelipatan

array([0, 2, 4, 6, 8])

In [8]:
#membuat array dummy
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [9]:
np.linspace(0,50,100)

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

In [10]:
#membuat array secara random
np.random.rand(3)

array([0.66666046, 0.88327639, 0.58922983])

In [11]:
np.random.rand(3,3)

array([[0.43916941, 0.98928792, 0.68346956],
       [0.0513923 , 0.34514962, 0.17030302],
       [0.32131426, 0.06321386, 0.57012215]])

In [12]:
#membuat data array random secara negatif dan positif
np.random.rand(5,7)

array([[0.15859775, 0.20112894, 0.69862383, 0.43308432, 0.92231954,
        0.25244295, 0.43127657],
       [0.21132544, 0.83560778, 0.33683447, 0.52959403, 0.24051324,
        0.27685322, 0.34062857],
       [0.21795967, 0.91245069, 0.70754522, 0.33503208, 0.81097388,
        0.07378605, 0.66515747],
       [0.48240193, 0.1317926 , 0.74045424, 0.03986763, 0.55591177,
        0.51970207, 0.79047857],
       [0.45810057, 0.03277232, 0.05235407, 0.46612326, 0.21725635,
        0.10178834, 0.83731891]])

In [13]:
np.random.randn(5,7)

array([[-3.65768776e-01, -1.86529235e+00,  3.42572943e-01,
         3.95872189e-02,  4.81291441e-02, -1.30204109e-01,
         6.74419919e-01],
       [-5.77239995e-02, -8.78628083e-02, -3.23046496e-01,
         3.14867048e-01, -5.75025346e-01, -7.91267032e-03,
         1.61018179e-03],
       [-1.87071051e-01, -1.21276013e+00,  5.44996817e-01,
        -7.30903547e-02, -1.23055095e+00, -8.19625756e-01,
         6.16873589e-01],
       [ 3.55393523e-01,  1.15382941e+00, -2.73259879e-01,
        -4.90021439e-01,  1.84983991e-01,  6.53338839e-01,
         6.83969359e-01],
       [-6.07532378e-01, -3.34092719e-01, -4.39023457e-01,
        -1.93296764e+00,  6.40193722e-01, -4.44745955e-01,
        -6.98343572e-01]])

In [14]:
#membuat data array random bilangan bulat
np.random.randint(1,50,10)

array([24, 28, 10,  5, 43, 33, 48, 10, 47, 32])

In [15]:
arr = np.arange(25)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr.reshape(5,5) #mengubah tampilan array dari 1D menjadi 2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr.max() #nilai array terbesar

24

In [19]:
arr.min() #nilai array terkecil

0

In [20]:
arr.argmax()#nilai pada index terbesar

24

In [21]:
arr.argmin() #nilai pada index terkecil

0

In [22]:
arr.sum() #menjumlahkan semua array

300